# Generated by Django 3.2.3 on 2021-05-26 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя файла')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('upload', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('marker', models.CharField(choices=[('GOOD', 'Хорошо'), ('BAD', 'Плохо'), ('SKIP', 'Пропущен')], max_length=50, verbose_name='Метка')),
                ('marker_detail', models.TextField(blank=True, verbose_name='Уточнение метки')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cam_name', models.CharField(max_length=50, verbose_name='Камера')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.photo', verbose_name='Фотография')),
            ],
        ),
    ]
