# Generated by Django 3.2.3 on 2021-05-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='upload',
        ),
        migrations.AddField(
            model_name='photo',
            name='img',
            field=models.ImageField(default=' ', upload_to='uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
