# Generated by Django 3.2.3 on 2021-05-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20210527_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='marker_detail',
        ),
        migrations.AddField(
            model_name='photo',
            name='bad_marker_detail',
            field=models.TextField(blank=True, verbose_name='Уточнение плохой метки'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.ImageField(default='default.png', upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='marker',
            field=models.CharField(blank=True, choices=[('GOOD', 'Хорошо'), ('BAD', 'Плохо'), ('SKIP', 'Пропущен')], max_length=50, verbose_name='Метка'),
        ),
    ]
