# Generated by Django 3.2.3 on 2021-05-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20210527_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='marker',
            field=models.CharField(choices=[('GOOD', 'Хорошо'), ('BAD', 'Плохо'), ('SKIP', 'Пропущен')], max_length=50, null=True, verbose_name='Метка'),
        ),
    ]
