# Generated by Django 3.2.3 on 2021-05-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_alter_photo_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='bad_marker_text',
            field=models.TextField(blank=True, verbose_name='Другая причина'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='bad_marker_detail',
            field=models.CharField(blank=True, choices=[('HIGH_TEMP', 'Высокая температура'), ('LOW_TEMP', 'Низкая температура'), ('OTHER', 'Другое')], max_length=50, verbose_name='Уточнение плохой метки'),
        ),
    ]
