# Generated by Django 3.2.3 on 2021-05-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20210527_1213'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['marker'], name='photos_phot_marker_b57e03_idx'),
        ),
    ]
