# Generated by Django 3.2.3 on 2021-05-27 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_alter_photo_marker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photometadata',
            name='photo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='photos.photo', verbose_name='Фотография'),
        ),
    ]
