# Generated by Django 3.2.3 on 2021-05-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_alter_photometadata_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photometadata',
            options={'verbose_name': 'Дополнительная информация', 'verbose_name_plural': 'Дополнительная информация'},
        ),
        migrations.AddField(
            model_name='photometadata',
            name='ftp_path',
            field=models.TextField(blank=True, verbose_name='Путь на ftp сервере'),
        ),
    ]
