# Generated by Django 3.2.3 on 2021-05-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0011_alter_photometadata_upload_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photometadata',
            name='upload_data',
            field=models.DateTimeField(blank=True, max_length=50, null=True, verbose_name='Дата и время сохренения изображения'),
        ),
    ]
