# Generated by Django 3.2.3 on 2021-07-27 07:55

from django.db import migrations, models
import photos.models
import storages.backends.sftpstorage


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0012_alter_photometadata_upload_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.ImageField(default='default.png', storage=storages.backends.sftpstorage.SFTPStorage(base_url='/ftp-media/'), upload_to=photos.models.photo_upload_path),
        ),
    ]
