# Generated by Django 3.2.3 on 2021-07-27 08:19

from django.db import migrations, models
import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0013_alter_photo_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.ImageField(default='default.png', upload_to=photos.models.photo_upload_path),
        ),
    ]
